# Generated by Django 5.0.7 on 2024-07-30 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0004_alter_cliente_table_alter_fornecedor_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='imagemprod',
            field=models.ImageField(default='produtos/imagem1.jpg', upload_to='produtos/'),
        ),
    ]
